// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEcAuIneLFI77f-_pM7tqXhtDNV5P9kcs',
    appId: '1:696673984351:web:d60aeaebcd68c5cf2360ea',
    messagingSenderId: '696673984351',
    projectId: 'fachub-c631c',
    authDomain: 'fachub-c631c.firebaseapp.com',
    storageBucket: 'fachub-c631c.firebasestorage.app',
    measurementId: 'G-VMC4E5NE50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABaqWKk3wwyFtcRbUpIw2jMfQUtwrU0GM',
    appId: '1:696673984351:android:fd697b78707ee3472360ea',
    messagingSenderId: '696673984351',
    projectId: 'fachub-c631c',
    storageBucket: 'fachub-c631c.firebasestorage.app',
  );

}